### ISSUE TITLE
add more uniprot data to the gene index (to mirror the one we have for evidence)

### ISSUE THREAD

**Issue by emepyc** [opentargets/data_pipeline#120]
@deniseOme commented on [Mon May 08 2017](https://github.com/opentargets/webapp/issues/125)

On https://www.targetvalidation.org/target/ENSG00000175164, there is no info re. 

Subunit:
Subcellular location:
UniProt Keywords:

However subcellular location and keywords seem to be available in UniProt:
http://www.uniprot.org/uniprot/P16442#subcellular_location

Same behaviour in beta:
https://beta.opentargets.io/target/ENSG00000175164

---

@emepyc commented on [Tue May 09 2017](https://github.com/opentargets/webapp/issues/125#issuecomment-300246463)

Probably a data issue: we may not be in sync with latest version of uniprot?
@ckongEbi can you please take a look? It is probably fine to close this issue if that is the case

---

@ckongEbi commented on [Tue May 09 2017](https://github.com/opentargets/webapp/issues/125#issuecomment-300294432)

we can see this information in **17.04_uniprot-data/uniprot-gene/P16442** 
![screen shot 2017-05-09 at 21 32 51](https://cloud.githubusercontent.com/assets/6169985/25871493/94349c14-34ff-11e7-9b23-9b1f62dfdec2.png)

But those section are empty in 17.04_gene-data/genedata/ENSG00000175164
![screen shot 2017-05-09 at 21 33 56](https://cloud.githubusercontent.com/assets/6169985/25871516/ae9bd752-34ff-11e7-9dcb-c063ada683e0.png)

suggesting this happens during gene-merging step @apierleoni ? This is the same in 17.02 data, @emepyc can we move this to "data_pipeline" repo

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #176](https://github.com/opentargets/platform/issues/176) via [**ZenHub**](https://www.zenhub.com/)
