### ISSUE TITLE
Query by drug trade names works selectively 

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data_pipeline#149]
@apierleoni @mkarmona can you help? 
@emepyc @deniseOme @iandunham 

1) This search by tradename works
http://targetvalidation.org/api/latest/public/search?q=humira
![screen shot 2017-06-16 at 11 54 33](https://user-images.githubusercontent.com/6169985/27224136-76f8d4e0-528b-11e7-9b76-efcd8cc3f04d.png)

2) This didn't , as the tradename it is missing in the `17.04_search-data/drugs/chembl_drugs/`, though present in chembl, probably a parsing issue at the `--sea` step ? 
http://targetvalidation.org/api/latest/public/search?q=viagra
![screen shot 2017-06-16 at 12 01 31](https://user-images.githubusercontent.com/6169985/27224171-94d12f3a-528b-11e7-9464-0532793a4025.png)

**Comment by ElaineMcA** [comment]
Closing issue and linking to drug index work on search - project ticket already open to address
