### ISSUE TITLE
Integration of Target Tractability data

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/data_pipeline#239]
Chris Radoux from ChEMBL is working on the Target Tractability project which is based on the GSK Target Tractability pipeline. Open Targets received the tractability score data in July 2018.

- [x] Become familiar with the data and define how it will be included in the platform.
- [x] Implementation of data injection.

Liaise with tractability project to include data from [DrugEBIlity](https://www.ebi.ac.uk/chembl/drugebility) and [pharos (NIH)](pharos.nih.gov).

More details [here](https://docs.google.com/spreadsheets/d/1kMVh2JybvJdh00xtkQWjfKCZIMiReLPdSUXShDb33HQ/edit?ts=5a672eae#gid=669895092)

**Comment by ElaineMcA** [comment]
All actions completed.
