### ISSUE TITLE
Text Mining: Title is not shown completely in Text Mining evidence section

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/data_pipeline#251]
Observed behaviour
Title of the 3rd paper (http://www.targetvalidation.org/evidence/ENSG00000124557/HP_0000118) is shown as "Altered expression of Butyrophilin (" instead of "Altered expression of Butyrophilin (BTN) and BTN-like (BTNL) genes in intestinal inflammation and colon cancer."

Expected behaviour
See above.

Environment
[How did you see the bug?]

Version: Website
Browser: Safari

First raised here: https://github.com/opentargets/webapp/issues/245

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #184](https://github.com/opentargets/platform/issues/184) via [**ZenHub**](https://www.zenhub.com/)
