### ISSUE TITLE
Text Mining: Text to highlight Target and Disease not always displayed 

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/data_pipeline#252]
Observed behaviour
When looking at the Text Mining Evidence for the following Associations, for some PMIDs the text that contains Target and Disease is not displayed and therefore the items are not highlighted.

http://www.targetvalidation.org/evidence/ENSG00000174059/EFO_0002428
Papers: Nr. 2 (PMID: 28321124), Nr. 3 (28920959) and Nr. 5 (PMID: 29100302) - in these three examples the abstract stops mid-way through a sentence.

http://www.targetvalidation.org/evidence/ENSG00000091704/EFO_0000616
Papers: Nr. 3 (PMID: 28834963) and Nr. 4 (PMID: 28966012) - in these two examples the abstract also is cut-off mid-way through a sentence.

Expected behaviour
Target and Disease highlighted.

Environment
[How did you see the bug?]

Version: on website
Browser: Safari

First raised here: https://github.com/opentargets/webapp/issues/240

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #185](https://github.com/opentargets/platform/issues/185) via [**ZenHub**](https://www.zenhub.com/)
