### ISSUE TITLE
OT API Target endpoint is returning wrong ChEMBL_id

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/data_pipeline#273]
This drug LUMILIXIMAB `http://www.targetvalidation.org/summary?drug=CHEMBL2109151` , the target associated is `FCER2`. 

But if we looked at the API `http://api.opentargets.io/v3/platform/private/target/ENSG00000104921` the synonyms is fine but the id **(CHEMBL_2940)** is wrong.

![image](https://user-images.githubusercontent.com/6169985/39580151-627a5726-4ee0-11e8-9d89-9a20e3201d7a.png)

If we looked at the the ChEMBL endpoint it returns 
![image](https://user-images.githubusercontent.com/6169985/39580219-90c65972-4ee0-11e8-8531-f8704e99c98b.png)

It looks like the `target_chembl_id` is used instead of the `molecule_chembl_id` in our data_pipeline ChEMBL plugin `https://github.com/opentargets/data_pipeline/blob/master/mrtarget/plugins/gene/chembl.py`

@gkos-bio any immediate thoughts? 
Cc: @iandunham @mkarmona @elipapa

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #181](https://github.com/opentargets/platform/issues/181) via [**ZenHub**](https://www.zenhub.com/)
