### ISSUE TITLE
Systems Biology Gene Sets (Evidence)

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/data_pipeline#277]
@MichaelaEBI commented on [Tue Mar 06 2018](https://github.com/opentargets/data_release/issues/73)

Include Systems Biology-derived gene sets in the Open Targets platform under "Pathways & Systems Biology"

- [x] Map out [process to include Systems Biology gene sets](https://docs.google.com/document/d/16YI0wy4mij3hMF_l-NKdCf-oedQFRgxbtlxF4xXFUPc/edit)
- [ ] Generate sample data (JSON) from IBD Key Driver Gene Set paper
- [ ] Identify and curate sample papers that identify key driver genes for various diseases
- [ ] Validate and process sample JSON file using pipeline code
- [ ] Define changes that need to be made throughout the platform

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #167](https://github.com/opentargets/platform/issues/167) via [**ZenHub**](https://www.zenhub.com/)
