### ISSUE TITLE
OTAR015: Integrate Cancer Dependency Map as Evidence

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/data_pipeline#292]
The Cancer Dependency Project Paper has been submitted and after the meeting on June 22nd, 2018, Francesco made the manuscript and data available to us so that we can start defining how the data will fit into the Open Targets Platform.

- [x] Read Cancer DepMap paper & become familiar with the data.
- [ ] Define inclusion and scoring of the data.
- [ ] Specify backend and frontend implementation details.
- [ ] Implement in data_pipeline.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #163](https://github.com/opentargets/platform/issues/163) via [**ZenHub**](https://www.zenhub.com/)
