### ISSUE TITLE
two or more ENS IDs for SNORA2

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/data_pipeline#30]
Nice to see that we also incorporate the ncRNA gene trees from Ensembl described by Pignatelli et al. :) in the Platform.

I may have spotted some inconsistencies. When I searched for SNORA2, I get to https://www.targetvalidation.org/target/ENSG00000202343 but the ID of the chimp orthologue did not match to the one in Ensembl:

http://www.ensembl.org/Homo_sapiens/Gene/Compara_Tree?db=core;g=ENSG00000199959;r=1:84277321-84277457;t=ENST00000363089

Then I realised the ENS ID of SNORA2 did not agree either.
So we also have:

https://www.targetvalidation.org/target/ENSG00000199959 and also

https://www.targetvalidation.org/target/ENSG00000206647

This seems to happen to other SNORAs such as SNORA22:

https://www.targetvalidation.org/search?src=q:SNORA2

When searching for the Ensembl gene ID (from Ensembl) for both SNORA2 and 22, there are no diseases associated with them. But for the other IDs (that we link to SNORA2 and SNORA22), there seems to be associations...

**Comment by ElaineMcA** [comment]
@gkos-bio - can I close this or is this still valid and needs Ensembl f-up?  Thanks,

Elaine

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #187](https://github.com/opentargets/platform/issues/187) via [**ZenHub**](https://www.zenhub.com/)
