### ISSUE TITLE
Make Ensembl.py use standard MySQL port

### ISSUE THREAD

**Issue by Docproc** [opentargets/data_pipeline#330]
Ensembl.py connects to the public Ensembl MySQL server to get a list of gene stable IDs. Currently is connects on the non-standard MySQL port 5306; this should be changed to 3306 (the standard port) - see [this blog post](http://www.ensembl.info/2013/05/02/database-port-changes/):

> This is in response to comments from users that many institutions and businesses do not allow access to remote resources on non-standard port numbers. The older 5306 was such a non-standard port number. We are beginning a migration which will see Ensembl host current release databases on the default MySQL port 3306

**Comment by afaulconbridge** [comment]
Do you want to have a go at fixing this with a branch and a pull request @Docproc ?

**Comment by afaulconbridge** [comment]
Also, we should try to open new issues on opentargets/platform rather than on here directly. The plan is to turn off the issue tracker on opentargets/data_pipeline eventually, once the remaining issues can be closed. @ElaineMcA can you migrate this issue across please?

**Comment by Docproc** [comment]
Will do. I was looking at the code to see if there's an easy way to avoid the use of the public MySQL database server completely, but it seems that there isn't (no suitable file to download, and no "get all genes" REST API endpoint).

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #153](https://github.com/opentargets/platform/issues/153) via [**ZenHub**](https://www.zenhub.com/)
