### ISSUE TITLE
wrong order in therapeutic area codes / labels in association object

### ISSUE THREAD

**Issue by emepyc** [opentargets/data_pipeline#93]
In the `association object -> disease -> efo_info -> therapeutic_area` we store the `labels` and the `codes` of the therapeutic areas as 2 independent arrays. The ordering of both are not always the same, so for example we see:

```
          "therapeutic_area": {
            "labels": [
              "hematological system disease",
              "neoplasm"
            ],
            "codes": [
              "EFO_0000616",
              "EFO_0005803"
            ]
          },
```
where EFO_0000616 is the code for neoplasm and EFO_0005803 is the code for hematological system disease.

Example from the rest api:
http://targetvalidation.org/api/latest/public/association/filter?disease=EFO_0001642

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #175](https://github.com/opentargets/platform/issues/175) via [**ZenHub**](https://www.zenhub.com/)
